language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -q -r requirements.txt
before_script:
  - python -m pylint ./routes/ --exit-zero
# command to run tests
script:
  - python -m pytest -v
