language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -q -r requirements.txt
# command to run tests
script:
  - python -m pylint ./routes/
  - python -m pytest -v