name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install -q -r requirements.txt
          python -m pytest -v
  deploy:
    needs: [build]
    runs-on: [ubuntu-latest]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: config zappa
        run: |
          echo "${{ secrets.ZAPPA_SETTINGS }}" > zappa_settings.json 
      - name: config python
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install zappa
      - name: deploy dev
        if: github.event_name == 'push'
        run: |
          pipenv run zappa
