name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install -q -r requirements.txt
          python -m pytest -v
  deploy:
    needs: [build]
    runs-on: [ubuntu-latest]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python3.8 -m venv deploy-env
          source deploy-env/bin/activate
          pip install -q -r requirements-prod.txt
          pip install zappa
      - name: deploy dev
        if: github.event_name == 'push'
        run: |
          source deploy-env/bin/activate
          echo ${{ secrets.ZAPPA_SETTINGS }} > zappa_settings.json 
          zappa update dev --quiet
